### ISSUE TITLE
代理速度非常慢

### ISSUE THREAD

**Issue by wgetnz** [FunnyWolf/pystinger#3]
经过测试，1G带宽下，PHP proxy内网的速度非常慢，是否有解决方法？

**Comment by FunnyWolf** [comment]
> 经过测试，1G带宽下，PHP proxy内网的速度非常慢，是否有解决方法？

可以在stinger_client 中将--sockettimeout参数调节到0.1或更小,可以加快速度.另外stinger默认有休眠机制,一段时间没有数据后会休眠3秒才传输一次数据,再次传输数据后恢复正常传输

**Comment by wgetnz** [comment]
> > 经过测试，1G带宽下，PHP proxy内网的速度非常慢，是否有解决方法？
> 
> 可以在stinger_client 中将--sockettimeout参数调节到0.1或更小,可以加快速度.另外stinger默认有休眠机制,一段时间没有数据后会休眠3秒才传输一次数据,再次传输数据后恢复正常传输

感谢
